name: RailsCI
on: [push, pull_request]

jobs:
  linters_and_tests:
    name: LintersAndTests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Ruby Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          
      - name: Run linters
        run: |
          bundle exec rubocop --fail-level W --display-only-fail-level-offenses --parallel
 
      - name: Create dot env file
        run: |
          touch .env
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env  
          echo "AUD_ID=${{ secrets.AUD_ID }}" >> .env  
          echo "FRONT_URL=${{ secrets.FRONT_URL }}" >> .env  
      - name: run rspec
        run: bundle exec rspec